server {
    listen 80 default_server;
    server_name _;
    server_tokens off;

    root /var/lib/rosetta/acme;

    location ^~ /.well-known/acme-challenge/ {
        default_type text/plain;
        limit_except GET HEAD { deny all; }
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}
